version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   environment:
  #     DB_CONN_STRING: 'Server=db;Database=servers;Uid=root;Pwd=mysqlrootpass;'
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysqluser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mysqlpass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysqlrootpass'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./QSB.Data/Database/Schema/MySQL.ddl:/docker-entrypoint-initdb.d/init.sql
volumes:
    db_data: {}